# Generated by Django 4.2.3 on 2023-07-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='isr',
        ),
    ]
