# Generated by Django 4.2.3 on 2023-07-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0002_remove_message_isr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modeo',
        ),
    ]
