# Generated by Django 4.2.3 on 2023-07-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifaction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
